// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinKlinik.Infrastructure.Persistence;

#nullable disable

namespace MinKlinik.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MinKlinik.Domain.Entities.Behandler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speciale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Behandlere");
                });

            modelBuilder.Entity("MinKlinik.Domain.Entities.Behandlingstype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EgenbetalingsBeløb", "MinKlinik.Domain.Entities.Behandlingstype.EgenbetalingsBeløb#EgenbetalingsBeløb", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Beløb");

                            b1
                                .ToJson("EgenbetalingsBeløb")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Behandlingstyper");
                });

            modelBuilder.Entity("MinKlinik.Domain.Entities.Konsultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BehandlerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BehandlingstypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EgenbetalingsBeløb", "MinKlinik.Domain.Entities.Konsultation.EgenbetalingsBeløb#EgenbetalingsBeløb", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Beløb");

                            b1
                                .ToJson("EgenbetalingsBeløb")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Tidspunkt", "MinKlinik.Domain.Entities.Konsultation.Tidspunkt#Tidsinterval", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Fra");

                            b1.Property<DateTime>("Til");

                            b1
                                .ToJson("Tidspunkt")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Konsultationer");
                });

            modelBuilder.Entity("MinKlinik.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CprNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patienter");
                });
#pragma warning restore 612, 618
        }
    }
}
